[31mCMake Error at /home/bobxu/ros2_humble/install/rosidl_adapter/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
  tutorial_interfaces --arguments-file
  /home/bobxu/ros_sycl_ws/build/tutorial_interfaces/rosidl_adapter__arguments__tutorial_interfaces.json
  --output-dir
  /home/bobxu/ros_sycl_ws/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces
  --output-file
  /home/bobxu/ros_sycl_ws/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces.idls)
  returned error code 1:

  Error processing 'int num' of 'tutorial_interfaces/Num': ''int' is an
  invalid message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/bobxu/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/bobxu/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/bobxu/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/home/bobxu/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/home/bobxu/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/home/bobxu/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
      super(Type, self).__init__(
    File "/home/bobxu/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'int' is an invalid message
  name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /home/bobxu/ros2_humble/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:16 (rosidl_generate_interfaces)

[0m
